language: node_js
node_js:
  - "0.12"
before_install:
  - "npm install"
  - "npm install -g istanbul"
  - "npm install -g mocha"
  - "make build"
script:
  - npm test
after_success:
  - make coveralls